# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.
name: R Package CI for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies on Windows
        run: |
          choco install jags
          choco install miktex
          choco install rtools
        shell: cmd

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install remotes package
        run: |
          Rscript -e \"install.packages('remotes')\"
        shell: cmd

      - name: Install package dependencies
        run: |
          Rscript -e \"install.packages(c('smacof', 'ellipse', 'plyr', 'vegan'))\"
        shell: cmd

      - name: Install basicspace from GitHub
        env:
          GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          Rscript -e \"remotes::install_github('cran/basicspace', force = TRUE)\"
        shell: cmd

      - name: Set CRAN mirror and install other R package dependencies
        env:
          GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          Rscript -e \"options(repos = c(CRAN = 'https://cloud.r-project.org/')); install.packages(c('rjags', 'ggplot2', 'knitr'))\"
        shell: cmd

      - name: Install rcmdcheck package
        run: |
          Rscript -e \"install.packages('rcmdcheck')\"
        shell: cmd

      - name: Check
        run: |
          Rscript -e \"rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')\"
        shell: cmd

      - name: Test (optional)
        run: |
          Rscript -e \"devtools::test() \"
        shell: cmd

    env:
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

